### PR TITLE
MNT: rerender

### LINKED ISSUE #12: @conda-forge-admin please rerender
@conda-forge-admin please rerender

### PR DESCRIPTION
**Pull request by conda-forge-linter**
Hi! This is the friendly automated conda-forge-webservice.

I've rerendered the recipe as instructed in #12.

Here's a checklist to do before merging.
- [ ] Bump the build number if needed.

Fixes #12

### CODE REVIEW

**Comment by ocefpaf** [comment]
Did really do anything :-/
This recipe is quite old, let me see if I can fix it. Hold on...

**Comment by mwcraig** [comment]
@ocefpaf -- I can do the updating if you want, let me know. I've got some $$ from astropy now to keep these sorts of things running so not a big deal.

**Comment by ocefpaf** [comment]
> @ocefpaf -- I can do the updating if you want, let me know.

I only re-did the recipe with grayskull. Usually that does the trick.

> I've got some $$ from astropy now to keep these sorts of things running so not a big deal.

Cool! Maybe you can do that, re-generate these recipes with grayskull to ensure they have "modern" enough.

**Comment by mwcraig** [comment]
> Maybe you can do that, re-generate these recipes with grayskull to ensure they have "modern" enough.

I've been going through them as new releases are done and updating. Some of the current recipes as the software equivalent of archaeological finds 😀

**Comment by mwcraig** [comment]
Thanks, @ocefpaf!

**Pull request merged**
